language: java

script: mvn -DargLine="-DdatabaseEngine=h2" clean verify
notifications:
  email: false
  
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
      
notifications:
  slack: rair-bestteam:vFeB90JXODiCNEFApbH8BKCe