language: java

script: mvn -DargLine="-DdatabaseEngine=h2" clean verify

notifications:
  email: false
  slack: rair-bestteam:vFeB90JXODiCNEFApbH8BKCe
  
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
      
cache:
  directories:
      - $HOME/.m2